# Generated by Django 4.1.3 on 2022-12-02 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('namecountry', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('namezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('invoiceno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('invoicedate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('stockcode', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'produit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('idzone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('namezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('stockcode', models.OneToOneField(db_column='stockcode', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dashboard.produit')),
                ('unitprice', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appartenir',
                'managed': False,
            },
        ),
    ]
