# Generated by Django 4.1.3 on 2022-12-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('idzone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('namezone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'zone',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Avoir',
        ),
    ]
