# Generated by Django 4.1.3 on 2022-12-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_zone_delete_avoir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
