# Generated by Django 4.1.3 on 2022-12-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailfacture',
            fields=[
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('detailfacture_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'detailfacture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('stock_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='appartenir',
            name='stockcode',
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
        migrations.DeleteModel(
            name='Appartenir',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
